### ISSUE TITLE
Incorrect block number in certifiers-of

### ISSUE THREAD

**Issue by Insoleet** [ucoin-io/ucoin#150]
http://metab.ucoin.io:9201/wot/certifiers-of/8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU

You can see that some certifications are declared to have been emitted on block "28287".

If you check the block 28287, these certifications were actually emitted on other block numbers : 
http://metab.ucoin.io/blockchain/Block/28287
28285, 28283, 28275, ...

If we take a look at this node : 
http://metab.ucoin.io:9212/wot/certifiers-of/8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU
We can see that the numbers here are correct.

**Comment by c-geek** [comment]
Indeed, being developing the multibranch feature I encountered a similar issue.

It seems the bug comes from a previous refactoring, here: https://github.com/ucoin-io/ucoin/blob/9b980d8b5dd794bcb79de76eccf24691d30406b4/app/service/BlockchainService.js#L476

This bug is a deep flaw, even if not breaking UCP. Thanks!

**Comment by c-geek** [comment]
Fixed in v0.12.
