### ISSUE TITLE
Error "signature does not match" but the UID was still published

### ISSUE THREAD

**Issue by Insoleet** [ucoin-io/ucoin#171]
Using latest cutecoin dev version, I tried to connect with my account "inso" on FairMoney.

I couldn't connect, so I tried to register instead.I got an error message "The signature does not match". 
The UID was still published and I was able to connect to the identity... So I wonder what happened there ?

Could be linked to https://github.com/ucoin-io/cutecoin/issues/218

I tried again with a fake account named "superman", but it did not print any error this time.

**Comment by M5oul** [comment]
I had to publish again my identity on my server. That strange. On my server in `identity.json` file there is two identity but without nicknames.

**Comment by c-geek** [comment]
This bug is a bit old now, and I've tried several strategies with [ucoin-cli](https://github.com/ucoin-io/ucoin-cli) which are, after generating a legit and signed identity:

* modify signature before publishing
* modify UID before publishing
* modify timestamp before publishing

I always receive a 400 HTTP error "signature does not match" and the identity is not published.

I close the issue, do not hesitate to reopen it if it happens again and you know how to reproduce it.
