### ISSUE TITLE
CPU flag still taken into account?

### ISSUE THREAD

**Issue by scith** [ucoin-io/ucoin#306]
Hello,
Is the --cpu flag still taken into account in the new version?
I tried "ucoind stop", "ucoind config --cpu 0.3" then "ucoind start" but ucoin_default is taking 50% CPU in "top"

Thanks

**Comment by c-geek** [comment]
Well yes, you can have a look at ~/.config/ucoin/ucoin_default/conf.json and see CPU value being changed.

But the --cpu option does not mean uCoin will use exactly this value, the option is only concerning proof-of-work computation.

So sometimes uCoin will use more than --cpu value because it processes documents, crawl the network etc., but sometime it will use just nothing as it does not need to compute PoW all the time (actually, it *cannot*) and do not crawl the network all the time either.

**Comment by c-geek** [comment]
Also, uCoin is monothreaded. It only uses 1 of your cores whatever happens, so it won't ever use all your CPU unless you have a mono-CPU server :-)

**Comment by scith** [comment]
OK I see :) Yes I have a mono-CPU 1.6Ghz so not much to share at the moment unfortunately... I guess it was because of this file processing you mentionned.
Thanks
