### ISSUE TITLE
api commands wot/certified-by and wot/certifiers-of don't work on a non member

### ISSUE THREAD

**Issue by vtexier** [ucoin-io/ucoin#53]
We can see non members in the wot to sign them.
But to verify who else signed them, and who are signed by them, it will be nice that we can get this information from the api.

Could the wot/certified-by and wot/certifiers-of work on a newcomer uid/pubkey ?

**Comment by c-geek** [comment]
The `wot/certified-by` and `wot/certifiers-of` methods cannot provide this feature since it implies the pubkey/uid is unique, which isn't always true for non-members.

However, `wot/lookup` already does half the job by providing signatures coming from others. It lacks however the other part: signatures *made by* the targeted uid/pubkey.

I will add this information for next version (v0.10.4).

**Comment by c-geek** [comment]
Feature added. You can test with http://metab.ucoin.io/wot/lookup/vit for example.

**Comment by vtexier** [comment]
Great ! Just a last request, could we have the uids in the "others" list like in the "signed" list ?

**Comment by vtexier** [comment]
I'm really stuck here, I can not properly display a newcomer graph with `wot/lookup`.
For all certifiers and certified by the newcomer, I need : 

* uid
* pubkey
* isMember

`wot/lookup` only gives me : 
certifiers : pubkey only
certified by : uid, pubkey

I can retrieve uids for certifiers by making one lookup by certifier, but I lack "isMember" whatever I do...

Could you add "isMember" status in "signed" list ?
Could you add "isMember" status and "uid" in "others" list ?

That way the infos I need will be complete.

**Comment by c-geek** [comment]
> Great ! Just a last request, could we have the uids in the "others" list like in the "signed" list ?

We can't absolutely give this information, since we have 2 cases:

* **the signatory is a member**. In this case, we can give the uid since *it is known* and cannot be changed
* **the signatory is not a member**. Here, the uid is not yet decided, it has not been written in the blockchain. The signatory is still in the sandbox of non-members and may have multiple ptoential uids (but at least 1!).

As a workaround solution, I can give you *an array* of possible uids. In the case of a member (or ex-member), this array would have only 1 entry. In the other case, it would have 1 or more.

> Could you add "isMember" status in "signed" list ?

Yes. And a "wasMember" field too.

> Could you add "isMember" status and "uid" in "others" list ?

Same answer :-)

**Comment by vtexier** [comment]
Excellent ! I buy your workaround for 100 MB !

To sum up, we'll have : 

* the **"uid"** field will be in the two lists as an **array of uids**. one for a member, one or more for a non member.
* the **"isMember"** field in the two lists.

**Comment by c-geek** [comment]
What I will do is:

* add the array of uids in "others" list
* add an `isMember` and `wasMember` in "others" list
* add an `isMember` and `wasMember` in "signed" list

So I won't turn the "others" list uid field into an array.
