### ISSUE TITLE
Consider implementing crosschain transactions

### ISSUE THREAD

**Issue by Insoleet** [ucoin-io/ucoin#68]
Consider implementing crosschain transactions. This would stregthen the "multi-currency" design of ucoin.

Users could swap money between different blockchains. 

For reference, mercuryex implements crosschain transactions for bitcoin-like currencies : 
http://mercuryex.com/

**Comment by taoeffect** [comment]
:+1:

**Comment by c-geek** [comment]
Ok, from what I've read, uCoin protocol (UCP) would need 2 changes for this algorithm to be possible:

* `x for H(x)` field to force secret's revelation
* transaction time lock for refunding

That's completely possible, and I agree with you guys this feature is really desirable. I guess it will be added to the next protocol version.

**Comment by taoeffect** [comment]
> That's completely possible, and I agree with you guys this feature is really desirable. I guess it will be added to the next protocol version.

That's awesome news! uCoin is just getting better and better! :smile: :+1:

**Comment by c-geek** [comment]
Edit: other examples:

http://wiki.bitshares.org/index.php/DPOS/Atomic_Cross-Chain_Trading

**Comment by c-geek** [comment]
After some deeper studies, uCoin protocol has to make some important changes to be compliant: it has to be more similar to Bitcoin's ouputs unlock mechanism rather than our too restrictive "transaction to pubkeys" mechanism.

We would have the following changes:

* so transactions will rely on unlock conditions for a given source (necessary for `x for H(x)` unlock condition + refunding tx)
* these conditions will be a combination of propositions with AND and OR operators along with parenthesis
* conditions are evaluated when a transaction tries to consume the refered inputs
* transactions need an extra `Locktime` field which would avoid tx inclusion in a block if blocktime is too early compared to tx inputs (refunding tx)
* transactions have to be forgeable *offline* (refunding tx)

We won't, however, make a scripting system of Bitcoin's level (too complicated for my skills and level - I want to avoid bugs). We will implement a basic system with the following grammar and words:

* `(` and `)` characters
*  ̀AND` and `OR` operators
* `SIG()`, `XHX()`

The simplicity will be our ally here.

**Comment by Insoleet** [comment]
Wow this looks awesome ! I did not expect to see this feature coming so fast :) Excellent job sir !
Just wondering, I can't find the definition of SIG and XHX keywords any where. Could you write some lines in Protocol.md about it ?

**Comment by c-geek** [comment]
Sure, I've added the following sections:

* [Conditions matching](https://github.com/ucoin-io/ucoin/blob/master/doc/Protocol.md#condition-matching)
* [SIG and XHX functions](https://github.com/ucoin-io/ucoin/blob/master/doc/Protocol.md#sig-and-xhx-functions)

**Prefer reading examples**, I guess it is the easier to understand. Explanations are not so good, I will completely rewrite the protocol soon for a more convenient reading & to avoid ambiguities.

**Comment by Insoleet** [comment]
Ok, I did not fully understand on a first pass, I'll read again later. Maybe consider describing the use cases of SIG and XHX in the future protocole rewrite !
