### ISSUE TITLE
Weird block mined

### ISSUE THREAD

**Issue by Insoleet** [ucoin-io/ucoin#82]
http://metab.ucoin.io/blockchain/block/15348

The transaction on this block got the same sender and receiver. How could this be validated ?

**Comment by c-geek** [comment]
Well ... the protocol does not avoid this kind of transaction: https://github.com/ucoin-io/ucoin/blob/master/doc/Protocol.md#transactions

I don't see the utility of making such transactions, however.

**Comment by Insoleet** [comment]
So, should this be a bug or not ?

It throws an exception into cutecoin because the sender (who is the same as the receiver), is filtered of the transaction.

**Comment by c-geek** [comment]
We should not allow this in next version of UCP.

**Comment by c-geek** [comment]
I am reconsidering the issue: actually this is a source transformation, from UD to TX, and it can even happen TX to TX.

I agree the purpose of this kind of transaction is not obvious, yet I don't really want to add an exception for this specific case. Because even if I add a rule like:

    « A transaction with exactly the same issuers and recipients, with the exact amounts from each issuer to each recipient. »

can easily be circumvented by making a transaction with a very little change in the amounts.

Maybe this would be an implementation concern to avoid adding such transactions in the blockchain.
