### ISSUE TITLE
Crash during init at salt step

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/ucoin#87]
When init my node, I entered my salt and the init command crash:
```bash
ucoind init metab.ucoin.io 9201
[?] UPnP does not seem available. Switch to manual network configuration? Yes
[?] IPv4 interface: eth0 46.101.0.25
[?] IPv6 interface: None
[?] Port: 6666
[?] Remote IPv4 eth0 46.101.0.25
[?] Remote IPv6 None
[?] Remote port: 6666
[?] Network: use UPnP to open remote port? (easier) No
[?] You need a keypair to identify your node on the network. Would you like to auto[?] You need a keypair to identify your node on the network. Would you like to automatically generate it? No
[?] Key's salt: moul@moul.re

/usr/lib/node_modules/ucoin/app/lib/wizard.js:111
        var obfuscated = conf.passwd.replace(/./g, '*');
                                     ^
TypeError: Cannot call method 'replace' of undefined
    at /usr/lib/node_modules/ucoin/app/lib/wizard.js:111:38
    at fn (/usr/lib/node_modules/ucoin/node_modules/async/lib/async.js:579:34)
    at Object._onImmediate (/usr/lib/node_modules/ucoin/node_modules/async/lib/async.js:495:34)
    at processImmediate [as _immediateCallback] (timers.js:330:15)

```

**Comment by M5oul** [comment]
Answering no to the first answer (uPnP) my node download well.

**Comment by M5oul** [comment]
So, to works fine when I:
* manual configure the network
* generate a key
What is the key? The identity of the member of something different related to node identity?

**Comment by JBitD** [comment]
I've run into the same bug after entering the salt, but I also went the other way.
This first time installed I answered `y` to generating a key because the wiki said it would ask for my key, but it generates one after pressing `y` so the wiki should be changed to "In the other case, you have to answer `n` and will be asked for your personal key materials:"
After it generated a key two blue progress bars were filled and it was done. I was able to start the node with pm2, but the node never showed up in CuteCoin. And later when I tried to change the key typing `ucoind wizard` a hollow cursor box appears on the next line and it does nothing forever. 
It might be good to add that I see the "root does not have permission to access the dev dir" warning and installing with --unsafe-perm results in `uncoind --version` not working, and even becoming root with `sudo -i` doesn't solve it, but that's probably unrelated.
I'm using 3.13.0-53-generic on a 64-bit system.
